name: Continuous Integration and Deployment

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build Docker Image
        run: docker build -t racetree:1.0 .
  
  deploy:
    name: Deploy to Heroku
    needs: build-and-test
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main') && (github.event_name == 'push') || github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Docker Image
        run: docker-compose up --build -d
      
      - name: Heroku Container Registry Log in
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Tag and Push Docker Image to Heroku
        run: |
          docker tag racetree:1.0 registry.heroku.com/racetree/web
          docker push registry.heroku.com/racetree/web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release the Image on Heroku
        run: heroku container:release web -a racetree
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    


      
